# .goreleaser.yaml
version: 2
project_name: mlc-markitdown

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/server/main.go
    binary: mlc-markitdown

archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - Dockerfile

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: hmsoft0815
    name: mlcmarkitdown
